export function PrivacyContent(){return <div className="policy-content">
 <p>Effective September 8, 2026 · Operator: John Prodromidis</p>
 <h3>Your builds and price notes</h3><p>The iPhone app stores build configurations, names, notes and personal price quotes on your device. It does not require an account or upload those records to our server. Device backups managed by Apple may include app data, depending on your settings.</p>
 <p>On the website, guest builds are stored in that browser. If you choose the signed-in cloud garage, we store your builds, draft and price notes with a site-specific account identifier so only that account can retrieve them. Sign-in is provided by ChatGPT. Your device garage and cloud garage are separate.</p>
 <h3>Sharing and backups</h3><p>A build link includes the vehicle, selected parts, purchase stages and budget amounts. Anyone you give that link to can read those details. It excludes your build name, notes and personal unit prices. A backup file includes names, notes, prices, saved builds and the draft. Only share backups with people you trust.</p>
 <h3>Service providers and external links</h3><p>The website uses OpenAI Sites and Cloudflare for hosting, sign-in and storage. These services process technical information such as IP addresses and request logs to operate and secure the site. The iPhone builder and catalog run locally; opening a retailer, partner-program, website link or support email uses an external service and its own privacy practices.</p>
 <h3>Commerce and affiliate disclosure</h3><p>The app may show product source links and partner-program application links for affiliate, reseller, dealer or distributor paths. Current links are reference and application links only; no affiliate tracking, wholesale checkout or dropship fulfillment is active. Paid links must be clearly labeled before any commission or resale link goes live.</p>
 <h3>Tracking and permissions</h3><p>We have not added advertising, behavioral analytics, location collection or cross-app tracking. The app does not request camera, contacts, microphone or photo-library access. Exporting a file uses the system share sheet; you choose where it goes.</p>
 <h3>Retention and deletion</h3><p>Build records remain until you delete them. Settings → Delete app data removes builds, drafts and price notes from the selected garage. Device data may also be removed by clearing browser storage or uninstalling the app. Exported files and device backups must be managed separately. Deleting this app’s data does not delete your ChatGPT account. Infrastructure security logs and provider backups follow the hosting providers’ retention policies.</p>
 <h3>Questions and requests</h3><p>Email <a href="mailto:johnprodromidis1@gmail.com?subject=Build%20Lab%20privacy">johnprodromidis1@gmail.com</a> for privacy questions or help with access, correction or deletion. Information you send in an email is used to respond to your request.</p>
 </div>;}
export function SupportContent(){return <div className="policy-content"><p>For help, email <a href="mailto:johnprodromidis1@gmail.com?subject=Build%20Lab%20support">johnprodromidis1@gmail.com</a>. Include your device, app version, what you tried, and the error you saw. Avoid sending passwords or private build notes.</p><h3>Where are my builds?</h3><p>Device builds stay in the browser or iPhone app where you saved them. Cloud builds appear only in the same signed-in account. Use Export backup before changing devices, clearing storage or uninstalling.</p><h3>What is supported?</h3><p>This catalog covers 2018–2023 Wrangler JL Unlimited four-door 3.6L gasoline Sport, Sahara and Rubicon builds with standard factory suspension, plus a first 2024 Sahara 4xe parts batch. TJ, JK, JT, two-door, diesel, 392, Xtreme Recon and other 4xe trims are not yet supported.</p><h3>Prices and fitment</h3><p>Prices are dated source snapshots or your own quotes. Inventory is not live. Partner-program links do not create a sale, commission or dealer order until approved account credentials and terms are added. The preview is illustrative and does not show every accessory. Confirm the exact product, complete combination and installation sequence with a qualified installer before buying.</p><h3>Offline use</h3><p>The packaged iPhone app includes its builder, catalog and preview assets. Saved device builds, price calculations and comparisons work without an internet connection. Retailer websites, partner-program pages and sending email require connectivity. The browser website requires a connection to load.</p><p>Independent aftermarket planning software. Not affiliated with Jeep, Stellantis or the listed parts brands.</p></div>;}
