import assert from "node:assert/strict";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { EXPECTED_BUNDLE_ID, EXPECTED_LIVE_SITES_VERSION, EXPECTED_VERSION, runPreflight } from "../scripts/app-store-preflight.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));

test("App Store preflight keeps release guardrails aligned", async () => {
  const report = await runPreflight(root);
  const failures = report.checks
    .filter((item) => !item.ok)
    .map((item) => item.label)
    .join("\n");

  assert.equal(report.expected.bundleId, EXPECTED_BUNDLE_ID);
  assert.equal(report.expected.version, EXPECTED_VERSION);
  assert.equal(EXPECTED_LIVE_SITES_VERSION, 124);
  const labels = new Set(report.checks.map((item) => item.label));
  assert.ok(labels.has("screenshot plan covers iPhone and iPad targets"));
  assert.ok(labels.has("screenshot plan requires native signed/TestFlight captures"));
  assert.ok(labels.has("screenshot plan rejects browser or generated final screenshots"));
  assert.ok(labels.has("screenshot plan protects private capture data"));
  assert.ok(labels.has("readiness records the current regression count"));
  assert.ok(labels.has("readiness records the catalog depth proof strip"));
  assert.ok(labels.has("readiness records the latest Sites version"));
  assert.ok(labels.has("readiness records the signing-profile gate"));
  assert.ok(labels.has("readiness records blank blocked-target guidance"));
  assert.ok(labels.has("readiness records paused partner-target guidance"));
  assert.ok(labels.has("readiness records paused application export guidance"));
  assert.ok(labels.has("readiness records paused application notes panel"));
  assert.ok(labels.has("readiness records status-filtered application order"));
  assert.ok(labels.has("readiness records blocked and paused reset controls"));
  assert.ok(labels.has("readiness records submitted and approved launch follow-up panel"));
  assert.ok(labels.has("readiness records paid-link launch proof checklist"));
  assert.ok(labels.has("readiness records partner launch evidence rows"));
  assert.ok(labels.has("readiness records future checkout guardrails"));
  assert.ok(labels.has("readiness records commerce-mode readiness map"));
  assert.ok(labels.has("readiness records neutral build-advisor positioning"));
  assert.ok(labels.has("readiness records owner-intent starter packs"));
  assert.ok(labels.has("readiness records installer quote checklist"));
  assert.ok(labels.has("readiness records shared independence disclosure"));
  assert.ok(labels.has("README handoff includes the live public site"));
  assert.ok(labels.has("README records the latest Sites version"));
  assert.ok(labels.has("README records the signing-profile gate"));
  assert.ok(labels.has("README records blank blocked-target guidance"));
  assert.ok(labels.has("README records paused partner-target guidance"));
  assert.ok(labels.has("README records paused application export guidance"));
  assert.ok(labels.has("README records paused application notes panel"));
  assert.ok(labels.has("README records status-filtered application order"));
  assert.ok(labels.has("README records blocked and paused reset controls"));
  assert.ok(labels.has("README records submitted and approved launch follow-up panel"));
  assert.ok(labels.has("README records paid-link launch proof checklist"));
  assert.ok(labels.has("README records partner launch evidence rows"));
  assert.ok(labels.has("README records future checkout guardrails"));
  assert.ok(labels.has("README records commerce-mode readiness map"));
  assert.ok(labels.has("README records market-positioning memo"));
  assert.ok(labels.has("README records owner-intent starter packs"));
  assert.ok(labels.has("README records installer quote checklist"));
  assert.ok(labels.has("README records shared independence disclosure"));
  assert.ok(labels.has("Codemagic prep enforces the registered Bundle ID"));
  assert.ok(labels.has("Codemagic prep derives build numbers from Codemagic"));
  assert.ok(labels.has("Codemagic prep rejects wrong IDs and remote shells"));
  assert.ok(labels.has("Codemagic prep verifies the offline mobile bundle"));
  assert.ok(labels.has("Codemagic prep updates both Xcode build configurations"));
  assert.ok(labels.has("TestFlight workflow checks signing profile before archive"));
  assert.ok(labels.has("Codemagic signing check names the missing profile gate"));
  assert.ok(labels.has("Codemagic signing check rejects non-App Store profiles"));
  assert.ok(labels.has("Codemagic guide records the current regression count"));
  assert.ok(labels.has("Codemagic guide records the catalog depth proof strip"));
  assert.ok(labels.has("Codemagic guide records the latest Sites version"));
  assert.ok(labels.has("Codemagic guide records blank blocked-target guidance"));
  assert.ok(labels.has("Codemagic guide records paused partner-target guidance"));
  assert.ok(labels.has("Codemagic guide records paused application export guidance"));
  assert.ok(labels.has("Codemagic guide records paused application notes panel"));
  assert.ok(labels.has("Codemagic guide records status-filtered application order"));
  assert.ok(labels.has("Codemagic guide records blocked and paused reset controls"));
  assert.ok(labels.has("Codemagic guide records submitted and approved launch follow-up panel"));
  assert.ok(labels.has("Codemagic guide records paid-link launch proof checklist"));
  assert.ok(labels.has("Codemagic guide records partner launch evidence rows"));
  assert.ok(labels.has("Codemagic guide records future checkout guardrails"));
  assert.ok(labels.has("Codemagic guide records commerce-mode readiness map"));
  assert.ok(labels.has("Codemagic guide records market-positioning memo"));
  assert.ok(labels.has("Codemagic guide records owner-intent starter packs"));
  assert.ok(labels.has("Codemagic guide records installer quote checklist"));
  assert.ok(labels.has("Codemagic guide records shared independence disclosure"));
  assert.ok(labels.has("market-positioning memo names the neutral advisor wedge"));
  assert.ok(labels.has("market-positioning memo covers current competitor set"));
  assert.ok(labels.has("market-positioning memo keeps commerce claims constrained"));
  assert.ok(labels.has("market-positioning memo records template-pack implementation"));
  assert.ok(labels.has("starter recipes include new owner-intent packs"));
  assert.ok(labels.has("shop brief exports installer quote checklist"));
  assert.ok(labels.has("builder surfaces installer quote checklist"));
  assert.ok(labels.has("builder surfaces shared independence disclosure"));
  assert.ok(labels.has("builder surfaces partner launch evidence rows"));
  assert.ok(labels.has("builder surfaces future checkout guardrails"));
  assert.ok(labels.has("builder surfaces commerce-mode readiness map"));
  assert.ok(labels.has("commerce exports partner launch evidence rows"));
  assert.ok(labels.has("commerce exports future checkout guardrails"));
  assert.ok(labels.has("commerce exports commerce-mode readiness map"));
  assert.ok(labels.has("shop brief exports shared independence disclosure"));
  assert.ok(labels.has("privacy and support copy reuse shared independence disclosure"));
  assert.ok(labels.has("styles cover installer quote checklist states"));
  assert.ok(labels.has("styles cover partner launch evidence rows"));
  assert.ok(labels.has("styles cover future checkout guardrails"));
  assert.ok(labels.has("styles cover commerce-mode readiness map"));
  assert.ok(report.checks.length >= 61);
  assert.equal(report.ok, true, failures);
});
