import assert from "node:assert/strict";
import test, {after} from "node:test";
import {existsSync} from "node:fs";
import {readFile,readdir,mkdir,rm} from "node:fs/promises";
import {fileURLToPath,pathToFileURL} from "node:url";
import path from "node:path";
import {build} from "esbuild";
import {DatabaseSync} from "node:sqlite";
const root=fileURLToPath(new URL("..",import.meta.url));
const output=path.join(root,".sites-runtime","unit");
await mkdir(output,{recursive:true});
const sql=new DatabaseSync(":memory:");
for(const file of (await readdir(path.join(root,"drizzle"))).filter(f=>f.endsWith(".sql")).sort())sql.exec(await readFile(path.join(root,"drizzle",file),"utf8"));
const DB={prepare(query){const stmt=sql.prepare(query);const bound=(args=[])=>({bind(...a){return bound(a);},async all(){return{results:stmt.all(...args),success:true};},async first(){return stmt.get(...args)??null;},async run(){const r=stmt.run(...args);return{success:true,meta:{changes:Number(r.changes)}};}});return bound();}};
DB.batch=async(statements)=>{sql.exec('BEGIN');try{const result=[];for(const stmt of statements)result.push(await stmt.run());sql.exec('COMMIT');return result;}catch(error){sql.exec('ROLLBACK');throw error;}};
globalThis.__testEnv={DB};
function resolveLocal(specifier,resolveDir){
 const base=specifier.startsWith("@/")?path.join(root,specifier.slice(2)):path.resolve(resolveDir,specifier);
 for(const candidate of [base,base+".ts",base+".tsx",base+".json",path.join(base,"index.ts"),path.join(base,"index.tsx")]){
  if(existsSync(candidate))return candidate;
 }
 throw new Error(`Could not resolve ${specifier} from ${resolveDir}`);
}
async function module(file,name){
 const entry=path.join(root,file),outfile=path.join(output,name+".mjs");
 await build({absWorkingDir:root,stdin:{contents:await readFile(entry,"utf8"),sourcefile:path.basename(file),resolveDir:path.dirname(entry),loader:file.endsWith(".tsx")?"tsx":"ts"},outfile,bundle:true,format:"esm",platform:"node",plugins:[{name:"test-resolver",setup(b){
  b.onResolve({filter:/^cloudflare:workers$/},()=>({path:"env",namespace:"binding"}));
  b.onResolve({filter:/^@\//},args=>({path:resolveLocal(args.path,root)}));
  b.onResolve({filter:/^\./},args=>({path:resolveLocal(args.path,args.resolveDir)}));
  b.onResolve({filter:/^[^./]/},args=>({path:args.path,external:true}));
  b.onLoad({filter:/.*/,namespace:"binding"},()=>({contents:"export const env = globalThis.__testEnv;"}));
  b.onLoad({filter:/\.(ts|tsx)$/},async args=>({contents:await readFile(args.path,"utf8"),loader:args.path.endsWith(".tsx")?"tsx":"ts"}));
  b.onLoad({filter:/\.json$/},async args=>({contents:await readFile(args.path,"utf8"),loader:"json"}));
 }}]});
 return import(pathToFileURL(outfile).href);
}
const model=await module("lib/model.ts","model");
const api=await module("app/api/builds/route.ts","builds");
const drafts=await module("app/api/draft/route.ts","drafts");
const planning=await module("lib/planning.ts","planning");
const accountData=await module("app/api/data/route.ts","data");
const catalog=await module("app/api/catalog/route.ts","catalog");
const decimalInput=await module("lib/decimal-input.ts","decimal-input");
const catalogFilters=await module("lib/catalog-filters.ts","catalog-filters");
const garageFilters=await module("lib/garage-filters.ts","garage-filters");
const shopBrief=await module("lib/shop-brief.ts","shop-brief");
const commerce=await module("lib/commerce.ts","commerce");
const recipes=await module("lib/build-recipes.ts","build-recipes");
const {initialState,baseCatalog,categories,selectedParts,totalFor,buildIssues,stateSchema,fitsVehicle,partCompatibility,partSpecBadges,linePriceRangeLabel,publicBuildState,encodeSharedBuildState,decodeSharedBuildStatePayload,buildErrorsForOption,optionAddsBuildError}=model;
const {catalogFitScore,catalogSortOptions,compareCatalogParts,dimensionFilterOptions,hasCatalogFilter,matchesCatalogFilters}=catalogFilters;
const {allGarageFilter,filterGarageBuilds,garageConflictCount,garageSearchText,hasGarageFilter}=garageFilters;
const {buildShopBrief}=shopBrief;
const {partnerPrograms,partnerProgramsForParts,partnerProgramsForBuild,partnerApplicationPrioritiesForBuild,partnerApplicationTrackerStatusNames,commerceOffersForPart,commerceSummaryForPart,safeCommerceUrl,commerceDisclosure,noActiveCommerceDisclosure,buildAffiliateApplicationAnswers,buildAffiliateApplicationProfile,buildBlockedApplicationSupportDraft,buildBlockedApplicationSupportMailtoUrl,buildCommerceApplicationPack,buildPartnerApplicationLinks,buildPartnerApplicationTrackerCsv,buildPartnerApplicationTrackerText,buildPaidLinkDisclosurePack,buildPartnerOutreachDraftPack,buildPartnerOutreachEmailDraft,buildPartnerOutreachMailtoUrl,buildPartnerSubmissionReviewSheet,commerceApplicationChecklist,affiliateApplicationAnswers,affiliateApplicationProfileFields,sponsoredLinkReadinessChecklist,partnerSubmissionReviewChecklist,partnerSubmissionPrivateFields,paidLinkDisclosureSnippet,paidLinkLaunchChecklist,paidLinkLaunchProofFields,paidLinkLaunchStatus}=commerce;
const {buildRecipes}=recipes;
const base=()=>structuredClone(initialState);
const req=(user,method="GET",body,origin="https://test.local",query="")=>new Request("https://test.local/api/builds"+query,{method,headers:{...(user?{"oai-authenticated-user-id":user}:{}),origin,"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});
const badJson=(path,method="POST")=>new Request("https://test.local/api/"+path,{method,headers:{"oai-authenticated-user-id":"alice",origin:"https://test.local","Content-Type":"application/json"},body:"{"});
const jsonBody=(path,method,body)=>new Request("https://test.local/api/"+path,{method,headers:{"oai-authenticated-user-id":"alice",origin:"https://test.local","Content-Type":"application/json"},body:JSON.stringify(body)});

test("catalog has 104 unique variants with positive cent prices and HTTPS sources",()=>{
 assert.equal(baseCatalog.length,104);assert.equal(new Set(baseCatalog.map(p=>p.id)).size,104);
 for(const p of baseCatalog){assert.ok(Number.isInteger(p.priceCents)&&p.priceCents>0);assert.equal(new URL(p.url).protocol,"https:");}
});
test("catalog exposes at least fifteen visible choices per major part category",()=>{
 for(const category of categories){
  const categoryParts=baseCatalog.filter(p=>p.category===category);
  assert.ok(categoryParts.length>=15,`${category} only has ${categoryParts.length} variants`);
  assert.ok(planning.groupParts(categoryParts).length>=15,`${category} only shows ${planning.groupParts(categoryParts).length} choices`);
 }
});
test("starter build recipes use known compatible catalog selections",()=>{
 assert.ok(buildRecipes.length>=3);
 const catalogIds=new Set(baseCatalog.map(p=>p.id));
 for(const recipe of buildRecipes){
  const parsed=stateSchema.safeParse(recipe.state);
  assert.equal(parsed.success,true,parsed.success?"":`${recipe.name}: ${parsed.error.message}`);
  assert.ok(categories.includes(recipe.focus),`${recipe.name} uses unknown focus ${recipe.focus}`);
  const pickIds=Object.values(recipe.state.picks);
  assert.ok(pickIds.length>=2,`${recipe.name} should load a useful starting point`);
  for(const id of pickIds)assert.ok(catalogIds.has(id),`${recipe.name} references unknown part ${id}`);
  assert.equal(selectedParts(recipe.state,baseCatalog).length,pickIds.length,`${recipe.name} has unresolved selected parts`);
  assert.deepEqual(buildIssues(recipe.state,baseCatalog).filter(i=>i.level==="error"),[],`${recipe.name} should not start with hard fitment errors`);
 }
});
test("part spec badges expose key comparison details by category",()=>{
 const wheel=baseCatalog.find(p=>p.id==="method-MR70178550500");
 const tire=baseCatalog.find(p=>p.id==="nitto-217010");
 const lift=baseCatalog.find(p=>p.id==="aev-spacer");
 const bumper=baseCatalog.find(p=>p.id==="qrc-12057-0140");
 const winch=baseCatalog.find(p=>p.id==="warn-evo");
 const armor=baseCatalog.find(p=>p.id==="qrc-armor");
 assert.deepEqual(partSpecBadges(wheel).slice(0,3),["17 in rim","8.5 in wide","0 mm offset"]);
 assert.ok(partSpecBadges(tire).includes("Fits 17 in rim"));
 assert.ok(partSpecBadges(lift).includes("2 in lift"));
 assert.ok(partSpecBadges(bumper).includes("Stubby"));
 assert.ok(partSpecBadges(winch).some(label=>label.includes("lb pull")));
 assert.ok(partSpecBadges(armor).includes("JL 4-door"));
});
test("line price ranges reflect selected rim and tire quantity",()=>{
 const tire=baseCatalog.find(p=>p.id==="nitto-217180");
 const choices=[{...tire,priceCents:100},{...tire,id:"test-tire-high",priceCents:250}];
 assert.equal(linePriceRangeLabel(choices,base()),"$5.00 - $12.50");
 assert.equal(linePriceRangeLabel([],base()),"No prices");
});
test("commerce partner directory covers all affiliate reseller dealer and distributor paths",()=>{
 assert.equal(partnerPrograms.length,13);
 const names=partnerPrograms.map(p=>p.name);
 for(const name of ["Tire Rack","RealTruck","CARiD","4 Wheel Parts","CJ Pony Parts","MORryde Jeep","American Modified","Quadratec Wholesale","ExtremeTerrain","Turn 14 Distribution","Meyer Distributing","Premier Performance","ARB distributor network"])assert.ok(names.includes(name),name);
 for(const program of partnerPrograms){assert.equal(program.status,"application-needed");assert.equal(new URL(program.url).protocol,"https:");assert.ok(program.categories.length>0);}
 const realTruck=partnerPrograms.find(program=>program.id==="realtruck-affiliate");
 assert.equal(realTruck.network,"Impact");
 assert.match(realTruck.note,/Impact affiliate application path/);
  assert.ok(realTruck.requirements.length>=3);
  assert.ok(realTruck.requirements.some(item=>item.includes("account name, country, timezone, currency")));
 assert.ok(realTruck.requirements.some(item=>item.includes("password/account setup")||item.includes("password or account setup")));
 assert.ok(realTruck.requirements.some(item=>item.includes("Password format is invalid")&&item.includes("An unknown error occurred")));
 assert.ok(realTruck.requirements.some(item=>item.includes("Continue disabled")&&item.includes("refresh or retry later")));
 assert.ok(partnerPrograms.some(p=>p.relationship==="affiliate"));
 assert.ok(partnerPrograms.some(p=>p.relationship==="reseller"));
 assert.ok(partnerPrograms.some(p=>p.relationship==="dealer"));
 assert.ok(partnerPrograms.some(p=>p.relationship==="distributor"));
});
test("commerce offers keep exact source links first and mark monetized paths pending",()=>{
 const tire=baseCatalog.find(p=>p.id==="nitto-217020");
 const offers=commerceOffersForPart(tire);
 assert.equal(offers[0].partnerName,"Quadratec");
 assert.equal(offers[0].url,tire.url);
 assert.equal(offers[0].status,"active-source");
 assert.equal(offers[0].paid,false);
 assert.ok(offers.some(o=>o.partnerName==="Tire Rack"&&o.relationship==="affiliate"&&o.status==="application-needed"));
 assert.ok(offers.some(o=>o.partnerName==="Quadratec Wholesale"&&o.relationship==="dealer"));
 assert.ok(offers.every(o=>new URL(o.url).protocol==="https:"));
 assert.match(commerceSummaryForPart(tire),/Application needed/);
 assert.match(commerceDisclosure,/Paid links/);
 assert.match(noActiveCommerceDisclosure,/no affiliate tracking/);
 assert.throws(()=>safeCommerceUrl("http://example.com"),/HTTPS/);
});
test("commerce application pack exports selected partner paths and prep checklist",()=>{
 const state=base();state.picks={tires:"nitto-217020",lift:"aev-spacer"};state.stages={tires:"now",lift:"later"};
 const selected=[baseCatalog.find(p=>p.id==="nitto-217020"),baseCatalog.find(p=>p.id==="aev-spacer")];
 const programs=partnerProgramsForParts(selected);
 assert.equal(partnerProgramsForBuild(base(),baseCatalog).length,partnerPrograms.length);
 assert.deepEqual(partnerProgramsForBuild(state,baseCatalog).map(program=>program.id),programs.map(program=>program.id));
 assert.ok(programs.some(program=>program.name==="Tire Rack"));
 assert.ok(programs.some(program=>program.name==="ARB distributor network"));
 assert.ok(!programs.some(program=>program.name==="MORryde Jeep"));
 const priorities=partnerApplicationPrioritiesForBuild(state,baseCatalog);
 assert.equal(priorities[0].program.name,"RealTruck");
 assert.equal(priorities[0].selectedPartCount,2);
 assert.match(priorities[0].reason,/Matches 2 selected parts across Tires, Suspension/);
 assert.ok(priorities[0].score>priorities.at(-1).score);
 assert.ok(commerceApplicationChecklist.length>=5);
 assert.ok(affiliateApplicationAnswers.length>=7);
 assert.ok(affiliateApplicationProfileFields.length>=8);
 assert.ok(sponsoredLinkReadinessChecklist.length>=5);
 assert.ok(paidLinkLaunchChecklist.length>=5);
 assert.ok(paidLinkLaunchProofFields.length>=5);
 assert.ok(partnerSubmissionReviewChecklist.length>=5);
 assert.ok(partnerSubmissionPrivateFields.length>=5);
 assert.match(paidLinkDisclosureSnippet,/clearly labeled affiliate or sponsored/);
 assert.equal(partnerApplicationTrackerStatusNames.submitted,"Submitted");
 assert.equal(partnerApplicationTrackerStatusNames.blocked,"Blocked");
 const applicationStatuses={"realtruck-affiliate":"submitted","tire-rack-affiliate":"ready","turn-14-distribution":"approved"};
 const launchStatus=paidLinkLaunchStatus(priorities,applicationStatuses);
 assert.match(launchStatus,/Paid-link launch status/);
 assert.match(launchStatus,/Approved programs ready for tracking-link setup: 1 \(Turn 14 Distribution\)\./);
 assert.match(launchStatus,/Submitted applications still waiting on approval or terms: 1 \(RealTruck via Impact\)\./);
 assert.match(launchStatus,/Unapproved relevant programs still locked: \d+\./);
 assert.match(launchStatus,/only approved, partner-issued tracking URLs may be labeled affiliate or sponsored/);
 const pack=buildCommerceApplicationPack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(pack,/Jeep Build Lab partner application pack/);
 assert.match(pack,/Generated: 2026-09-14/);
 assert.match(pack,/Affiliate application profile fields/);
 assert.match(pack,/Website URL: https:\/\/jeep-build-lab\.johnprodromidis1\.chatgpt\.site\//);
 assert.match(pack,/Common application answers/);
 assert.match(pack,/Website or app description: Jeep Build Lab is an independent Wrangler JL build planner/);
 assert.match(pack,/Traffic or sales estimate: Use the current verified site analytics/);
 assert.match(pack,/Fulfillment role: Jeep Build Lab is currently a planning and referral experience/);
 assert.match(pack,/Sponsored-link readiness/);
 assert.match(pack,/Label every paid outbound link as sponsored or affiliate/);
 assert.match(pack,/Paid-link disclosure snippet/);
 assert.match(pack,/Disclosure: Jeep Build Lab may earn a commission from links clearly labeled affiliate or sponsored/);
 assert.match(pack,/Pre-publish paid-link checks/);
 assert.match(pack,/Launch proof to verify/);
 assert.match(pack,/Partner-issued tracking URL stored outside public source/);
 assert.match(pack,/Paid-link launch status/);
 assert.match(pack,/Approved programs ready for tracking-link setup: 1 \(Turn 14 Distribution\)\./);
 assert.match(pack,/Launch rule: only approved, partner-issued tracking URLs may be labeled affiliate or sponsored/);
 assert.match(pack,/Submission review checklist/);
 assert.match(pack,/Review every visible field, checkbox, opt-in, agreement and program term/);
 assert.match(pack,/Application tracker summary\n- To apply: \d+\n- Profile ready: 1\n- Submitted: 1\n- Approved: 1\n- Paused: 0\n- Blocked: 0\n- Next application: /);
 assert.match(pack,/Suggested application order/);
 assert.match(pack,/1\. RealTruck via Impact - Matches 2 selected parts across Tires, Suspension\. Tracker: Submitted\./);
 assert.match(pack,/Next outreach email draft/);
 assert.match(pack,/Subject: Jeep Build Lab partner application - CARiD/);
 assert.match(pack,/Current commerce posture: links are reference and application links only until a partner approves terms/);
 assert.match(pack,/Details to verify before sending: legal business name, applicant name, phone/);
 assert.match(pack,/Selected build source links/);
 assert.match(pack,/Source: Quadratec - https:\/\/www\.quadratec\.com\/p\/nitto\/ridge-grappler-tire/);
 assert.match(pack,/Application link: https:\/\/www\.tirerack\.com\/affiliate/);
 assert.match(pack,/Application tracker: Profile ready/);
 assert.match(pack,/Application tracker: Approved/);
 assert.match(pack,/Application prep checklist/);
 assert.match(pack,/1\. Confirm the legal business name/);
 assert.match(pack,/Owner notes\nApply before linking\./);
 assert.doesNotMatch(pack,/MORryde Jeep/);
 const links=buildPartnerApplicationLinks({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(links,/Jeep Build Lab partner application links/);
 assert.match(links,/Scope: 2 selected parts \(Tires, Suspension\)/);
 assert.match(links,/Paid links must be clearly labeled/);
 assert.match(links,/Sponsored-link readiness/);
 assert.match(links,/Application tracker summary/);
 assert.match(links,/Submission review checklist/);
 assert.match(links,/Next application: /);
 assert.match(links,/Suggested application order/);
 assert.match(links,/RealTruck via Impact - Matches 2 selected parts across Tires, Suspension\. Tracker: Submitted\./);
 assert.match(links,/1\. Tire Rack - Affiliate/);
 assert.match(links,/Application tracker: Profile ready/);
 assert.match(links,/Link: https:\/\/www\.tirerack\.com\/affiliate/);
 assert.match(links,/Turn 14 Distribution - Distributor/);
 assert.match(links,/Application tracker: Approved/);
 assert.doesNotMatch(links,/MORryde Jeep/);
 const tracker=buildPartnerApplicationTrackerCsv({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(tracker,/"Jeep Build Lab partner application tracker"/);
 assert.match(tracker,/"Build","Commission plan"/);
 assert.match(tracker,/"Scope","2 selected parts \(Tires, Suspension\)"/);
 assert.match(tracker,/"Rank","Program","Network","Relationship","Tracker status","Tracker note","Commerce status","Matched categories","Selected part count","Match reason","Application link","Requirements","Prep note","Next action"/);
 assert.match(tracker,/"1","RealTruck","Impact","Affiliate","Submitted","","Application needed","Tires; Suspension","2","Matches 2 selected parts across Tires, Suspension\."/);
 assert.match(tracker,/"Tire Rack","","Affiliate","Profile ready","","Application needed","Tires","1"/);
 assert.match(tracker,/"Submit the application after private business, tax, traffic and contact fields are verified\."/);
 assert.match(tracker,/"Use only approved tested tracking links and keep paid labels visible\."/);
 assert.doesNotMatch(tracker,/MORryde Jeep/);
 const trackerText=buildPartnerApplicationTrackerText({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(trackerText,/Jeep Build Lab partner application tracker summary/);
 assert.match(trackerText,/Application tracker summary/);
 assert.match(trackerText,/1\. RealTruck via Impact - Submitted/);
 assert.match(trackerText,/Next: Watch for approval, terms, tracking-link rules and any requested verification\./);
 assert.match(trackerText,/Link: https:\/\/realtruck\.com\/affiliate\//);
 assert.match(trackerText,/Reminder: Do not claim approved affiliate tracking/);
 const profile=buildAffiliateApplicationProfile({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(profile,/Jeep Build Lab affiliate application profile template/);
 assert.match(profile,/Audience: Jeep Wrangler JL owners comparing rims, tires, suspension, bumpers, winches and armor before buying/);
 assert.match(profile,/Catalog basis: 104 sourced variants with dated source snapshots/);
 assert.match(profile,/Build focus: Tires, Suspension/);
 assert.match(profile,/Fields to verify before submitting/);
 assert.match(profile,/Common application answers/);
 assert.match(profile,/Compliance disclosure: Paid links will stay inactive until the partner account is approved/);
 assert.match(profile,/Pricing and inventory basis: Catalog prices are dated source snapshots or user-entered notes/);
 assert.match(profile,/Suggested application order/);
 assert.match(profile,/Private fields/);
 assert.match(profile,/Application tracker: Submitted/);
 assert.match(profile,/Application tracker: Profile ready/);
 assert.match(profile,/Application tracker summary/);
 assert.match(profile,/Submission review checklist/);
 assert.match(profile,/Next application: /);
 assert.match(profile,/Next outreach email draft/);
 assert.match(profile,/Subject: Jeep Build Lab partner application - CARiD/);
 assert.match(profile,/Do not store passwords, banking info, tax IDs, private phone numbers or affiliate tracking credentials in the public app source/);
 assert.match(profile,/RealTruck via Impact/);
 assert.doesNotMatch(profile,/MORryde Jeep/);
 const answers=buildAffiliateApplicationAnswers({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(answers,/Jeep Build Lab affiliate application answer kit/);
 assert.match(answers,/Public profile basis/);
 assert.match(answers,/Next application target/);
 assert.match(answers,/Program: CARiD/);
 assert.match(answers,/Tracker status: To apply/);
 assert.match(answers,/Relationship: Affiliate/);
 assert.match(answers,/Application link: https:\/\/www\.carid\.com\/affiliate\.html/);
 assert.match(answers,/Match reason: Matches 2 selected parts across Tires, Suspension\./);
 assert.match(answers,/Next outreach email draft/);
 assert.match(answers,/Subject: Jeep Build Lab partner application - CARiD/);
 assert.match(answers,/Public site: https:\/\/jeep-build-lab\.johnprodromidis1\.chatgpt\.site\//);
 assert.match(answers,/Common application answers/);
 assert.match(answers,/Do not paste without verifying/);
 assert.match(answers,/Do not claim approved affiliate tracking, live checkout, dealer pricing, inventory ownership or dropship fulfillment/);
 assert.match(answers,/Build focus: Tires, Suspension/);
 const disclosure=buildPaidLinkDisclosurePack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(disclosure,/Jeep Build Lab paid-link disclosure pack/);
 assert.match(disclosure,/Use this disclosure only after partner approval/);
 assert.match(disclosure,/Disclosure snippet/);
 assert.match(disclosure,/Current commerce status/);
 assert.match(disclosure,/Paid-link launch status/);
 assert.match(disclosure,/Submitted applications still waiting on approval or terms: 1 \(RealTruck via Impact\)\./);
 assert.match(disclosure,/Application tracker summary/);
 assert.match(disclosure,/Pre-publish paid-link checks/);
 assert.match(disclosure,/Launch proof to verify/);
 assert.match(disclosure,/Clean-browser test date and expected landing page/);
 assert.match(disclosure,/Partner has approved the account and program terms/);
 assert.match(disclosure,/Placement rules/);
 assert.match(disclosure,/Label each individual paid link or button as sponsored or affiliate/);
 assert.match(disclosure,/Owner notes\nApply before linking\./);
 const draft=buildPartnerOutreachEmailDraft({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(draft,/Subject: Jeep Build Lab partner application - CARiD/);
 assert.match(draft,/Current build context: Commission plan - 2021 Wrangler JL Unlimited 4-door Sport, 3\.6L V6 gas/);
 assert.match(draft,/Application path: https:\/\/www\.carid\.com\/affiliate\.html/);
 const mailto=new URL(buildPartnerOutreachMailtoUrl({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses}));
 assert.equal(mailto.protocol,"mailto:");
 assert.equal(mailto.searchParams.get("subject"),"Jeep Build Lab partner application - CARiD");
 assert.match(mailto.searchParams.get("body"),/Hi CARiD team/);
 assert.match(mailto.searchParams.get("body"),/Current commerce posture: links are reference and application links only/);
 assert.doesNotMatch(mailto.searchParams.get("body"),/^Subject:/);
 const draftPack=buildPartnerOutreachDraftPack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(draftPack,/Jeep Build Lab partner outreach draft pack/);
 assert.match(draftPack,/Draft count: \d+ unsubmitted programs out of \d+ relevant programs\./);
 assert.match(draftPack,/Draft 1: CARiD/);
 assert.match(draftPack,/Tracker status: To apply/);
 assert.match(draftPack,/Subject: Jeep Build Lab partner application - CARiD/);
 assert.match(draftPack,/Do not send without verifying/);
 assert.match(draftPack,/Do not claim approved affiliate tracking, reseller terms, dealer pricing, wholesale checkout or dropship fulfillment/);
 assert.doesNotMatch(draftPack,/Draft 1: RealTruck/);
 const review=buildPartnerSubmissionReviewSheet({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses});
 assert.match(review,/Jeep Build Lab partner submission review sheet/);
 assert.match(review,/Target application/);
 assert.match(review,/Program: CARiD/);
 assert.match(review,/Owner-private or legal fields to verify on the live form/);
 assert.match(review,/Account name, legal business name, applicant name and DBA/);
 assert.match(review,/Program agreement acceptance, privacy terms and email marketing opt-in choices/);
 assert.match(review,/Submission review checklist/);
 assert.match(review,/Confirm the application is on the expected partner or network domain/);
 assert.match(review,/Before marking Submitted/);
 assert.match(review,/Suggested owner approval line/);
 assert.match(review,/I approve submitting the visible CARiD application fields/);
 const blockedStatuses={...applicationStatuses,"carid-affiliate":"blocked"};
 const blockedNotes={"carid-affiliate":"Partner network password screen rejected the account setup."};
 const blockedPack=buildCommerceApplicationPack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedPack,/Application tracker summary\n- To apply: \d+\n- Profile ready: 1\n- Submitted: 1\n- Approved: 1\n- Paused: 0\n- Blocked: 1\n- Next application: /);
 assert.match(blockedPack,/Tracker notes\n- CARiD: Partner network password screen rejected the account setup\./);
 assert.match(blockedPack,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 assert.match(blockedPack,/Reset a blocked program only after the password, account, eligibility or partner-site issue is resolved/);
 assert.match(blockedPack,/Next outreach email draft/);
 assert.match(blockedPack,/Subject: Jeep Build Lab partner application - 4 Wheel Parts/);
 const blockedAnswers=buildAffiliateApplicationAnswers({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedAnswers,/Program: 4 Wheel Parts/);
 assert.match(blockedAnswers,/Tracker status: To apply/);
 assert.match(blockedAnswers,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 const blockedLinks=buildPartnerApplicationLinks({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedLinks,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 const blockedProfile=buildAffiliateApplicationProfile({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedProfile,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 const blockedDisclosure=buildPaidLinkDisclosurePack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedDisclosure,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 assert.match(blockedDisclosure,/Blocked applications to resolve before launch: 1 \(CARiD\)\./);
 const blockedDraftPack=buildPartnerOutreachDraftPack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedDraftPack,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 assert.match(blockedDraftPack,/Jeep Build Lab blocked partner support ticket drafts/);
 assert.match(blockedDraftPack,/Subject: Partner application support - CARiD/);
 const supportDraft=buildBlockedApplicationSupportDraft({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(supportDraft,/Tracker note: Partner network password screen rejected the account setup\./);
 assert.match(supportDraft,/Public site: https:\/\/jeep-build-lab\.johnprodromidis1\.chatgpt\.site\//);
 assert.match(supportDraft,/Do not include in an ordinary support email/);
 assert.match(supportDraft,/Passwords, tax IDs, banking details/);
 const supportMailto=new URL(buildBlockedApplicationSupportMailtoUrl({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes}));
 assert.equal(supportMailto.protocol,"mailto:");
 assert.equal(supportMailto.searchParams.get("subject"),"Partner application support - CARiD");
 assert.match(supportMailto.searchParams.get("body"),/Hi CARiD support team/);
 assert.match(supportMailto.searchParams.get("body"),/Tracker note: Partner network password screen rejected the account setup\./);
 assert.match(supportMailto.searchParams.get("body"),/Build context: Commission plan - 2021 Wrangler JL Unlimited 4-door Sport, 3\.6L V6 gas/);
 assert.doesNotMatch(supportMailto.searchParams.get("body"),/^Subject:/);
 assert.doesNotMatch(supportMailto.searchParams.get("body"),/Passwords, tax IDs, banking details/);
 const blockedReview=buildPartnerSubmissionReviewSheet({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedReview,/Blocked application follow-up\n- CARiD: Partner network password screen rejected the account setup\./);
 const blockedTracker=buildPartnerApplicationTrackerCsv({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:blockedStatuses,applicationStatusNotes:blockedNotes});
 assert.match(blockedTracker,/"CARiD","","Affiliate","Blocked","Partner network password screen rejected the account setup\.","Application needed"/);
 assert.match(blockedTracker,/"Resolve password, account, eligibility or partner-site errors before retrying this application\."/);
 const pausedStatuses={...applicationStatuses,"realtruck-affiliate":"paused"};
 const pausedAnswers=buildAffiliateApplicationAnswers({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:pausedStatuses});
 assert.match(pausedAnswers,/Next application target\n- Program: CARiD/);
 assert.match(pausedAnswers,/Paused application follow-up\n- RealTruck via Impact: Paused by owner; reset when this program is worth pursuing again\./);
 assert.match(pausedAnswers,/Paused programs are skipped as next-application targets until reset to To apply or Profile ready\./);
 assert.match(pausedAnswers,/Subject: Jeep Build Lab partner application - CARiD/);
 const pausedLinks=buildPartnerApplicationLinks({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:pausedStatuses});
 assert.match(pausedLinks,/Application tracker summary\n- To apply: \d+\n- Profile ready: 1\n- Submitted: 0\n- Approved: 1\n- Paused: 1\n- Blocked: 0\n- Next application: CARiD \(To apply\)/);
 assert.match(pausedLinks,/Paused application follow-up\n- RealTruck via Impact: Paused by owner; reset when this program is worth pursuing again\./);
 const pausedDraftPack=buildPartnerOutreachDraftPack({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:pausedStatuses});
 assert.match(pausedDraftPack,/Paused application follow-up\n- RealTruck via Impact: Paused by owner; reset when this program is worth pursuing again\./);
 assert.match(pausedDraftPack,/Draft 1: CARiD/);
 assert.doesNotMatch(pausedDraftPack,/Draft 1: RealTruck/);
 const allPausedStatuses=Object.fromEntries(priorities.map(priority=>[priority.program.id,"paused"]));
 const noPausedDraft=buildPartnerOutreachEmailDraft({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:allPausedStatuses});
 assert.match(noPausedDraft,/No unblocked or unpaused partner application is ready to pursue/);
 const noPausedReview=buildPartnerSubmissionReviewSheet({name:"Commission plan",notes:"Apply before linking.",state,parts:baseCatalog,generatedAt:"2026-09-14T15:30:00.000Z",applicationStatuses:allPausedStatuses});
 assert.match(noPausedReview,/Target application\n- No relevant partner program found for this build\./);
 assert.match(noPausedReview,/Paused application follow-up\n- RealTruck via Impact: Paused by owner; reset when this program is worth pursuing again\./);
 assert.doesNotMatch(noPausedReview,/I approve submitting the visible RealTruck via Impact application fields/);
});
test("totals multiply individual wheels/tires, count kits once, and include allowances",()=>{
 const s=base();s.picks={wheels:"method-MR70178550900",tires:"nitto-217020",lift:"lift-16400-0073"};s.labor=50000;s.extras=30000;
 assert.equal(totalFor(s).subtotal,36600*5+43200*5+69995);
 assert.equal(totalFor(s).total,36600*5+43200*5+69995+80000);
 s.quantity=4;assert.equal(totalFor(s).subtotal,36600*4+43200*4+69995);
});
test("price entry preserves exact cents and rejects ambiguous or malformed amounts",()=>{
 for(const [text,cents] of [['0.29',29],['9.99',999],['.05',5],['1,234.56',123456],['100000.00',10000000],['12.',1200]]){
  assert.equal(decimalInput.parseDecimalUnits(text,2),cents);
  assert.equal(decimalInput.parseDecimalUnits(decimalInput.formatDecimalUnits(cents,2),2),cents);
 }
 for(const text of ['', '.', '-1', '1e4', '12,34', '1.234', 'Infinity', '12abc', '99999999999999999'])assert.equal(decimalInput.parseDecimalUnits(text,2),null);
});
test("finished tire and budget entries preserve valid previous values when input is incomplete or outside limits",()=>{
 const tire={places:1,min:300,max:350};
 assert.equal(decimalInput.finishDecimalInput('32.5',320,tire).value,325);
 for(const raw of ['', '3', '36', '32.55']){
  const result=decimalInput.finishDecimalInput(raw,320,tire);
  assert.equal(result.value,320);assert.match(result.message,/Kept 32.0/);
 }
 const dollars={places:2,min:0,max:10000000,emptyAsZero:true};
 assert.deepEqual(decimalInput.finishDecimalInput('',12999,dollars),{value:0,message:''});
 assert.equal(decimalInput.finishDecimalInput('100000.01',12999,dollars).value,12999);
 assert.deepEqual(decimalInput.finishDecimalInput('125.50',12999,dollars),{value:12550,message:''});
});
test("entered decimal allowances flow through the build total as integer cents",()=>{
 const state=base();state.picks={tires:'nitto-217020'};
 const options={places:2,min:0,max:10000000,emptyAsZero:true};
 state.labor=decimalInput.finishDecimalInput('1,250.29',state.labor,options).value;
 state.extras=decimalInput.finishDecimalInput('99.99',state.extras,options).value;
 assert.ok(stateSchema.safeParse(state).success);
 assert.equal(totalFor(state).total,43200*5+125029+9999);
});
test("18-inch tires on 17-inch rims produce an explicit conflict",()=>{
 const s=base();s.picks={tires:"nitto-217130"};assert.ok(buildIssues(s).some(i=>i.level==="error"&&i.message.includes("diameter mismatch")));
 s.stockRim=18;assert.ok(!buildIssues(s).some(i=>i.message.includes("diameter mismatch")));
});
test("changing trim surfaces an existing incompatible lift variant",()=>{
 const s=base();s.trim="Rubicon";s.picks={lift:"lift-16400-0073"};assert.ok(buildIssues(s).some(i=>i.level==="error"&&i.message.includes("Sport, Sahara")));
});
test("a tire above the source lift limit conflicts while other mechanical checks remain",()=>{
 const s=base();s.picks={tires:"nitto-217050",lift:"aev-spacer"};assert.ok(buildIssues(s).some(i=>i.level==="error"&&i.message.includes("limit")));
 s.trim="Rubicon";assert.ok(!buildIssues(s).some(i=>i.message.includes("limit")));assert.ok(buildIssues(s).some(i=>i.message.includes("rim width")));
});
test("malformed or fabricated shared state is rejected",()=>{
 assert.equal(stateSchema.safeParse({...base(),picks:{tires:"made-up"}}).success,false);
 assert.equal(stateSchema.safeParse({...base(),picks:{lift:"nitto-217050"}}).success,false);
 assert.equal(stateSchema.safeParse({...base(),labor:-1}).success,false);
 assert.equal(stateSchema.safeParse({...base(),quantity:999}).success,false);
 assert.equal(stateSchema.safeParse({...base(),year:2024,powertrain:"gas"}).success,false);
 assert.equal(stateSchema.safeParse({...base(),year:2024,trim:"Rubicon",powertrain:"4xe"}).success,false);
 assert.equal(stateSchema.safeParse({...base(),year:2023,trim:"Sahara",powertrain:"4xe"}).success,false);
 assert.equal(stateSchema.safeParse({...base(),stages:{wheels:"owned"}}).success,false);
});
test("shared build payload exposes only public build state",()=>{
 const state={...base(),year:2024,trim:"Sahara",powertrain:"4xe",stockRim:20,stockTire:32,budget:625000,labor:12550,extras:9999,picks:{tires:"nitto-217310-4xe",lift:"mopar-77072522ae-4xe"},stages:{tires:"now",lift:"later"},name:"Private trail name",notes:"secret notes",ownerId:"owner-1",savedTotal:1,prices:[{partId:"nitto-217310-4xe",priceCents:1}],customPrice:true};
 const payload=encodeSharedBuildState(state),json=decodeURIComponent(payload),parsed=JSON.parse(json);
 assert.deepEqual(Object.keys(parsed).sort(),["budget","extras","labor","picks","powertrain","quantity","stages","stockRim","stockTire","trim","vehicleCost","year"].sort());
 assert.doesNotMatch(json,/Private trail name|secret notes|ownerId|savedTotal|prices|customPrice/);
 assert.deepEqual(decodeSharedBuildStatePayload(payload),publicBuildState(state));
});
test("2024 Sahara 4xe keeps powertrain fitment explicit and supports 20-inch starting rims",()=>{
 const s={...base(),year:2024,trim:"Sahara",powertrain:"4xe",stockRim:20,stockTire:32,picks:{}};
 assert.equal(stateSchema.safeParse(s).success,true);
 assert.equal(fitsVehicle(baseCatalog.find(p=>p.id==="nitto-217330-4xe"),s),true);
 assert.equal(fitsVehicle(baseCatalog.find(p=>p.id==="mopar-77072522ae-4xe"),s),true);
 assert.equal(fitsVehicle(baseCatalog.find(p=>p.id==="method-MR70178550900"),s),false);
 assert.match(partCompatibility(baseCatalog.find(p=>p.id==="method-MR70178550900"),s),/2024/);
 const build={...s,picks:{tires:"nitto-217310-4xe",lift:"mopar-77072522ae-4xe"},stages:{tires:"now",lift:"later"}};
 assert.equal(totalFor(build).subtotal,46300*5+183540);
 assert.ok(!buildIssues(build).some(issue=>issue.level==="error"));
});
test("catalog recommendations distinguish vehicle fit from current-build conflicts",()=>{
 const state={...base(),year:2024,trim:"Sahara",powertrain:"4xe",stockRim:20,stockTire:32,picks:{tires:"nitto-217310-4xe",lift:"mopar-77072522ae-4xe"},stages:{tires:"now",lift:"later"}};
 const wheel17=baseCatalog.find(p=>p.id==="morphic-92615-3835");
 const tire20=baseCatalog.find(p=>p.id==="nitto-217330-4xe");
 assert.equal(fitsVehicle(wheel17,state),true);
 assert.equal(optionAddsBuildError(wheel17,state,baseCatalog),true);
 assert.match(buildErrorsForOption(wheel17,state,baseCatalog)[0].message,/Rim diameter mismatch/);
 assert.equal(optionAddsBuildError(tire20,state,baseCatalog),false);
});
test("catalog filters combine brand, line price, search terms and dimensions",()=>{
 const state={...base(),year:2024,trim:"Sahara",powertrain:"4xe",stockRim:20,stockTire:32,quantity:5,picks:{}};
 const tire=baseCatalog.find(p=>p.id==="nitto-217310-4xe");
 assert.equal(hasCatalogFilter({query:"ridge 217310",brand:"Nitto",price:"1000-2500",dimension:"rim:20"}),true);
 assert.equal(matchesCatalogFilters(tire,state,{category:"tires",query:"ridge 217310",brand:"Nitto",price:"1000-2500",dimension:"rim:20"}),true);
 assert.equal(matchesCatalogFilters(tire,state,{category:"tires",query:"ridge",brand:"BFGoodrich",price:"1000-2500",dimension:"rim:20"}),false);
 assert.equal(matchesCatalogFilters(tire,state,{category:"tires",query:"ridge",brand:"Nitto",price:"under-500",dimension:"rim:20"}),false);
 assert.equal(matchesCatalogFilters(tire,state,{category:"tires",query:"ridge",brand:"Nitto",price:"1000-2500",dimension:"rim:17"}),false);
 const options=dimensionFilterOptions(baseCatalog.filter(p=>p.category==="tires"),"tires");
 assert.ok(options.some(option=>option.value==="rim:20"&&/20-inch/.test(option.label)));
});
test("best-fit catalog sort promotes selected parts and matching build dimensions",()=>{
 const stock18={...base(),trim:"Sahara",stockRim:18,picks:{}};
 const wheel17=baseCatalog.find(p=>p.id==="method-MR70178550900");
 const wheel17Other=baseCatalog.find(p=>p.id==="method-MR70178550500");
 const tire17=baseCatalog.find(p=>p.id==="nitto-217020");
 const tire18=baseCatalog.find(p=>p.id==="nitto-217130");
 assert.equal(catalogSortOptions[0].value,"fit");
 assert.ok(catalogFitScore(tire18,stock18,baseCatalog)<catalogFitScore(tire17,stock18,baseCatalog));
 assert.equal([tire17,tire18].sort(compareCatalogParts("fit",stock18,baseCatalog))[0].id,"nitto-217130");
 assert.equal([tire17,tire18].sort(compareCatalogParts("low",stock18,baseCatalog))[0].id,"nitto-217020");
 const withSelectedWheel={...stock18,picks:{wheels:"method-MR70178550900"}};
 assert.ok(catalogFitScore(wheel17,withSelectedWheel,baseCatalog)<catalogFitScore(wheel17Other,withSelectedWheel,baseCatalog));
 assert.ok(catalogFitScore(tire17,withSelectedWheel,baseCatalog)<catalogFitScore(tire18,withSelectedWheel,baseCatalog));
});
test("garage filters search saved builds by vehicle, notes, parts, status and value",()=>{
 const mismatch={...base(),trim:"Sahara",stockRim:18,picks:{wheels:"method-MR70178550900"}};
 const hybrid={...base(),year:2024,trim:"Sahara",powertrain:"4xe",stockRim:20,stockTire:32,picks:{tires:"nitto-217310-4xe",lift:"mopar-77072522ae-4xe"},stages:{tires:"now",lift:"later"}};
 const stock=base();
 const builds=[
  {id:"gas-conflict",name:"17s on Sahara",notes:"Needs matching tires",state:mismatch,updatedAt:"2026-09-10T10:00:00.000Z",savedTotal:123000},
  {id:"hybrid",name:"Sahara 4xe beach plan",notes:"Ridge Grappler and Mopar lift",state:hybrid,updatedAt:"2026-09-13T10:00:00.000Z",savedTotal:415040},
  {id:"stock",name:"Baseline daily",notes:"No upgrades yet",state:stock,updatedAt:"2026-09-12T10:00:00.000Z",savedTotal:0},
 ];
 assert.equal(hasGarageFilter({query:"",powertrain:allGarageFilter,conflicts:allGarageFilter}),false);
 assert.ok(garageSearchText(builds[1],baseCatalog).includes("ridge grappler"));
 assert.equal(garageConflictCount(builds[0],baseCatalog),1);
 assert.deepEqual(filterGarageBuilds(builds,baseCatalog,{query:"ridge mopar",powertrain:"4xe",conflicts:"clean",sort:"updated-desc"}).map(b=>b.id),["hybrid"]);
 assert.deepEqual(filterGarageBuilds(builds,baseCatalog,{query:"",powertrain:allGarageFilter,conflicts:"needs-review",sort:"value-desc"}).map(b=>b.id),["gas-conflict"]);
 assert.deepEqual(filterGarageBuilds(builds,baseCatalog,{query:"",powertrain:allGarageFilter,conflicts:allGarageFilter,sort:"value-desc"}).map(b=>b.id),["hybrid","gas-conflict","stock"]);
 assert.deepEqual(filterGarageBuilds(builds,baseCatalog,{query:"",powertrain:allGarageFilter,conflicts:allGarageFilter,sort:"updated-asc"}).map(b=>b.id),["gas-conflict","stock","hybrid"]);
});
test("shop brief export groups staged parts, totals, source links and fitment notes",()=>{
 const state=base();state.picks={tires:"nitto-217020",lift:"aev-spacer"};state.stages={tires:"now",lift:"owned"};state.labor=12500;state.extras=5000;
 const brief=buildShopBrief({name:"Trail quote",notes:"Ask about alignment timing.",state,parts:baseCatalog,generatedAt:"2026-09-14T12:00:00.000Z"});
 assert.match(brief,/Jeep Build Lab shop brief/);
 assert.match(brief,/Build: Trail quote/);
 assert.match(brief,/Generated: 2026-09-14/);
 assert.match(brief,/2021 Wrangler JL Unlimited 4-door Sport/);
 assert.match(brief,/Buy now\n- Tires: Nitto Ridge Grappler/);
 assert.match(brief,/Already owned\n- Suspension: AEV 2/);
 assert.match(brief,/Price: \$432.00 x 5 = \$2,160.00/);
 assert.match(brief,/Upgrades left to fund: \$2,335.00/);
 assert.match(brief,/Source: Quadratec - https:\/\/www\.quadratec\.com\/p\/nitto\/ridge-grappler-tire/);
 assert.match(brief,/Commerce disclosure/);
 assert.match(brief,/Commerce options: Quadratec \(Product source, Source link\); Tire Rack \(Affiliate, Application needed\)/);
 assert.match(brief,/Fitment conflicts \(0\)/);
 assert.match(brief,/No blocking fitment conflicts detected/);
 assert.match(brief,/Shop confirmation checks \([1-9]/);
 assert.match(brief,/Owner notes\nAsk about alignment timing\./);
});
test("D1 route round-trip, price isolation, update ownership and delete ownership",async()=>{
 assert.equal((await api.GET(req(null))).status,401);
 assert.equal((await api.POST(req("alice","POST",{name:"A",notes:"",state:base()},"https://evil.example"))).status,403);
 const state=base();state.picks={tires:"nitto-217020"};
 const saved=await api.POST(req("alice","POST",{name:"Trail build",notes:"Weekend plan",state}));assert.equal(saved.status,200);const data=await saved.json();
 assert.equal(data.savedTotal,43200*5);
 assert.equal((await (await api.GET(req("alice"))).json()).builds[0].notes,"Weekend plan");
 assert.deepEqual((await (await api.GET(req("bob"))).json()).builds,[]);
 assert.equal((await api.POST(req("bob","POST",{id:data.id,name:"Stolen",notes:"",state}))).status,404);
 await api.DELETE(req("bob","DELETE",undefined,undefined,"?id="+data.id));
 assert.equal((await (await api.GET(req("alice"))).json()).builds.length,1);
 const quote=await catalog.PUT(req("alice","PUT",{partId:"nitto-217020",priceCents:40000}));assert.equal(quote.status,200);
 assert.equal((await (await catalog.GET(req("alice"))).json()).parts.find(p=>p.id==="nitto-217020").priceCents,40000);
 assert.equal((await (await catalog.GET(req("bob"))).json()).parts.find(p=>p.id==="nitto-217020").priceCents,43200);
 const updated=await api.POST(req("alice","POST",{id:data.id,name:"Updated",notes:"Fresh quote",state}));assert.equal(updated.status,200);assert.equal((await updated.json()).savedTotal,200000);
 assert.equal((await api.POST(req("alice","POST",{name:"Invalid",notes:"",state:{...state,picks:{wheels:"nitto-217020"}}}))).status,400);
 await catalog.DELETE(req("alice","DELETE",undefined,undefined,"?partId=nitto-217020"));
 assert.equal((await (await catalog.GET(req("alice"))).json()).parts.find(p=>p.id==="nitto-217020").priceCents,43200);
 await api.DELETE(req("alice","DELETE",undefined,undefined,"?id="+data.id));
 assert.deepEqual((await (await api.GET(req("alice"))).json()).builds,[]);
});
test("mutating API routes report malformed JSON as client errors",async()=>{
 assert.equal((await api.POST(badJson("builds"))).status,400);
 assert.equal((await catalog.PUT(badJson("catalog","PUT"))).status,400);
 assert.equal((await drafts.PUT(badJson("draft","PUT"))).status,400);
 assert.equal((await accountData.DELETE(badJson("data","DELETE"))).status,400);
 assert.equal((await accountData.DELETE(jsonBody("data","DELETE",null))).status,400);
});
test("new 17-inch rims conflict with retained 18-inch tires until matching tires are added",()=>{
 const state=base();state.trim="Sahara";state.stockRim=18;state.picks={wheels:"method-MR70178550900"};
 assert.ok(buildIssues(state).some(issue=>issue.level==="error"&&issue.message.includes("current tires fit 18")));
 state.picks.tires="nitto-217020";
 assert.ok(!buildIssues(state).some(issue=>issue.level==="error"&&issue.message.includes("diameter mismatch")));
});
test("purchase stages exclude owned items without hiding parts from final-build fitment",()=>{
 const state=base();state.picks={wheels:"method-MR70178550900",tires:"nitto-217130",lift:"aev-spacer"};
 state.stages={wheels:"owned",tires:"later",lift:"installed"};state.labor=60000;state.extras=15000;state.vehicleCost=3500000;
 const costs=planning.costPlan(state,baseCatalog);
 assert.equal(costs.now,0);assert.equal(costs.later,47200*5);assert.equal(costs.covered,36600*5+48900);
 assert.equal(costs.remaining,47200*5+75000);assert.equal(costs.dueNow,75000);assert.equal(costs.project,costs.remaining+3500000);
 assert.ok(buildIssues(state).some(i=>i.level==="error"&&i.message.includes("diameter mismatch")));
 state.stages.wheels="now";assert.equal(planning.costPlan(state,baseCatalog).dueNow,36600*5+75000);
});
test("legacy saved configurations gain defaults and comparisons include quantity and purchase stage",()=>{
 const legacy=base();delete legacy.stages;delete legacy.vehicleCost;delete legacy.powertrain;
 const restored=stateSchema.parse(legacy);assert.deepEqual(restored.stages,{});assert.equal(restored.vehicleCost,0);assert.equal(restored.powertrain,"gas");
 restored.picks={tires:"nitto-217020"};const other=structuredClone(restored);other.quantity=4;
 const rows=planning.compareRows(restored,other,baseCatalog);assert.equal(rows.filter(r=>r.changed).length,1);assert.equal(rows.find(r=>r.category==="tires").leftCost,43200*5);
 other.quantity=5;other.stages.tires="owned";assert.equal(planning.compareRows(restored,other,baseCatalog).find(r=>r.category==="tires").changed,true);
 assert.equal(planning.groupParts(baseCatalog).reduce((n,g)=>n+g.variants.length,0),104);
 assert.equal(stateSchema.safeParse({...base(),stages:{wheels:"free"}}).success,false);
 assert.equal(stateSchema.safeParse({...base(),picks:{tires:"nitto-217020"},stages:{tires:"owned"}}).success,true);
});
test("draft recovery keeps owners isolated and rejects stale concurrent writes",async()=>{
 const draft={name:"Trail draft",notes:"Still choosing",state:base(),buildId:null,lastSavedTotal:null};
 assert.equal((await drafts.GET(req(null))).status,401);
 assert.equal((await drafts.PUT(req("draft-a","PUT",{revision:0,draft},"https://evil.example"))).status,403);
 assert.equal((await drafts.PUT(req("draft-a","PUT",{revision:0,draft}))).status,200);
 const first=await (await drafts.GET(req("draft-a"))).json();assert.equal(first.revision,1);assert.equal(first.draft.name,"Trail draft");
 assert.equal((await (await drafts.GET(req("draft-b"))).json()).draft,null);
 assert.equal((await drafts.PUT(req("draft-a","PUT",{revision:0,draft:{...draft,name:"Stale first write"}}))).status,409);
 assert.equal((await drafts.PUT(req("draft-a","PUT",{revision:1,draft:{...draft,name:"Newest draft"}}))).status,200);
 assert.equal((await drafts.PUT(req("draft-a","PUT",{revision:1,draft:{...draft,name:"Stale update"}}))).status,409);
 assert.equal((await (await drafts.GET(req("draft-a"))).json()).draft.name,"Newest draft");
 assert.equal((await drafts.PUT(req("draft-a","PUT",{revision:2,draft:{...draft,state:{...base(),picks:{tires:"fictional"}}}}))).status,400);
});
test("guest catalog excludes personal prices and private data export/deletion stay owner scoped",async()=>{
 const state=base();state.picks={tires:"nitto-217020"};
 await api.POST(req("export-a","POST",{name:"Private A",notes:"Personal",state}));
 await api.POST(req("export-b","POST",{name:"Private B",notes:"Other",state}));
 await catalog.PUT(req("export-a","PUT",{partId:"nitto-217020",priceCents:12345}));
 const publicCatalog=await catalog.GET(req(null));assert.equal(publicCatalog.status,200);
 assert.equal((await publicCatalog.json()).parts.find(p=>p.id==="nitto-217020").priceCents,43200);
 assert.equal((await accountData.GET(req(null))).status,401);
 const backup=await (await accountData.GET(req("export-a"))).json();
 assert.equal(backup.builds.length,1);assert.equal(backup.builds[0].name,"Private A");assert.equal(backup.prices[0].priceCents,12345);
 assert.equal((await accountData.DELETE(req("export-a","DELETE",{confirm:"NO"}))).status,400);
 assert.equal((await accountData.DELETE(req("export-a","DELETE",{confirm:"DELETE MY APP DATA"},"https://evil.example"))).status,403);
 assert.equal((await accountData.DELETE(req("export-a","DELETE",{confirm:"DELETE MY APP DATA"}))).status,200);
 const erased=await (await accountData.GET(req("export-a"))).json();assert.equal(erased.builds.length,0);assert.equal(erased.prices.length,0);assert.equal(erased.draft,null);
 assert.equal((await (await accountData.GET(req("export-b"))).json()).builds[0].name,"Private B");
});
after(async()=>{sql.close();delete globalThis.__testEnv;await rm(output,{recursive:true,force:true});});
