const checkedAt = "2026-09-15";
const trims = ["Sport", "Sahara", "Rubicon"];
const bothPowertrains = ["gas", "4xe"];
const gasPowertrain = ["gas"];

const sources = {
  wheels: "https://www.quadratec.com/categories/jeep-wheel-accessories/wheels/vehicle/jeep-wrangler-jl",
  lift: "https://www.quadratec.com/vehicle/jeep-wrangler-jl-parts/lift-kits-suspension/lift-kits",
  bumpers: "https://www.quadratec.com/vehicle/jeep-wrangler-jl-parts/bumpers/front-bumpers",
  winches: "https://www.quadratec.com/categories/jeep_winches_recovery/vehicle/jeep-wrangler-jl",
  armor: "https://www.quadratec.com/categories/jeep_armor_protection/side_steps_rocker_bars/vehicle/jeep-wrangler-jl",
};

const catalogExpansion = [
  {
    id: "black-rhino-armory-1790ary85127g71",
    category: "wheels",
    brand: "Black Rhino",
    name: "Armory",
    variant: "17x9 - Gun Black",
    reference: "MPN 1790ARY-85127G71",
    priceCents: 39100,
    retailer: "Quadratec",
    url: sources.wheels,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { rim: 17, width: 9, backspacing: 4.5, finish: "black" },
    notes: "Quadratec JL wheel listing snapshot. Confirm lug nuts, hub rings, brake clearance, load rating and spare-carrier fitment before purchase."
  },
  {
    id: "fuel-d664-shok-d66417907545",
    category: "wheels",
    brand: "Fuel Off-Road",
    name: "D664 Shok",
    variant: "17x9 - Matte Black / machined dark tint",
    reference: "MPN D66417907545",
    priceCents: 33900,
    retailer: "Quadratec",
    url: sources.wheels,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { rim: 17, width: 9, backspacing: 4.5, finish: "black" },
    notes: "Quadratec JL wheel listing snapshot. Confirm lug nuts, hub rings, brake clearance, load rating and spare-carrier fitment before purchase."
  },
  {
    id: "black-rhino-kelso-1790kso85127m71",
    category: "wheels",
    brand: "Black Rhino",
    name: "Kelso",
    variant: "17x9 - Matte Black",
    reference: "MPN 1790KSO-85127M71",
    priceCents: 32600,
    retailer: "Quadratec",
    url: sources.wheels,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { rim: 17, width: 9, backspacing: 4.5, finish: "black" },
    notes: "Quadratec JL wheel listing snapshot. Confirm lug nuts, hub rings, brake clearance, load rating and spare-carrier fitment before purchase."
  },
  {
    id: "mammoth-general-1717-7973",
    category: "wheels",
    brand: "Mammoth",
    name: "General",
    variant: "17x9 - Black",
    reference: "Catalog 1717-7973",
    priceCents: 16999,
    retailer: "Quadratec",
    url: sources.wheels,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { rim: 17, width: 9, backspacing: 4.5, finish: "black" },
    notes: "Quadratec JL wheel listing snapshot. Confirm lug nuts, hub rings, brake clearance, load rating and spare-carrier fitment before purchase."
  },
  {
    id: "rugged-ridge-xhd-1530102",
    category: "wheels",
    brand: "Rugged Ridge",
    name: "XHD Aluminum Wheel",
    variant: "17x9 - Silver",
    reference: "MPN 15301.02",
    priceCents: 23999,
    retailer: "Quadratec",
    url: sources.wheels,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { rim: 17, width: 9, backspacing: 4.75, finish: "silver" },
    notes: "Quadratec JL wheel listing snapshot. Confirm lug nuts, hub rings, brake clearance, load rating and spare-carrier fitment before purchase."
  },
  {
    id: "rocktrix-rt117-matte-black",
    category: "wheels",
    brand: "RockTrix",
    name: "RT117",
    variant: "17x9 - Matte Black",
    reference: "Quadratec JL wheel listing",
    priceCents: 11999,
    retailer: "Quadratec",
    url: sources.wheels,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { rim: 17, width: 9, backspacing: 4.5, finish: "black" },
    notes: "Quadratec JL wheel listing snapshot. Confirm lug nuts, hub rings, brake clearance, load rating and spare-carrier fitment before purchase."
  },
  {
    id: "rough-country-25-suspension-lift",
    category: "lift",
    brand: "Rough Country",
    name: "Suspension Lift Kit",
    variant: "2.5 in",
    reference: "Quadratec JL lift listing",
    priceCents: 49995,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 2.5 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "teraflex-sport-st2-25",
    category: "lift",
    brand: "TeraFlex",
    name: "Sport ST2 Suspension System",
    variant: "2.5 in",
    reference: "Quadratec JL lift listing",
    priceCents: 158299,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 2.5 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "readylift-sst-25",
    category: "lift",
    brand: "ReadyLIFT",
    name: "SST Lift Kit",
    variant: "2.5 in",
    reference: "Quadratec JL lift listing",
    priceCents: 44399,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 2.5 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "teraflex-sport-st3-35",
    category: "lift",
    brand: "TeraFlex",
    name: "Sport ST3 Suspension System",
    variant: "3.5 in",
    reference: "Quadratec JL lift listing",
    priceCents: 274599,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 3.5 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "skyjacker-dual-rate-long-travel-25",
    category: "lift",
    brand: "Skyjacker",
    name: "Dual Rate Long Travel Suspension Lift Kit",
    variant: "2.5 in",
    reference: "Quadratec JL lift listing",
    priceCents: 116199,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 2.5 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "rough-country-35-suspension-lift",
    category: "lift",
    brand: "Rough Country",
    name: "Suspension Lift Kit",
    variant: "3.5 in",
    reference: "Quadratec JL lift listing",
    priceCents: 79995,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 3.5 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "fabtech-trail-performance-3",
    category: "lift",
    brand: "Fabtech",
    name: "Trail Performance Lift Kit",
    variant: "3 in",
    reference: "Quadratec JL lift listing",
    priceCents: 125499,
    retailer: "Quadratec",
    url: sources.lift,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2023,
    trims,
    powertrains: gasPowertrain,
    specs: { lift: 3 },
    notes: "Source listing snapshot. Tire clearance, driveshaft, caster, bump-stop and alignment needs vary by trim and installed weight."
  },
  {
    id: "quadratec-carnivore-front-bumper",
    category: "bumpers",
    brand: "Quadratec",
    name: "Carnivore Front Bumper",
    variant: "Full width - winch ready",
    reference: "Quadratec JL bumper listing",
    priceCents: 69999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { winchMount: true },
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and exact winch fit before purchase."
  },
  {
    id: "rampage-rock-rage-front-bumper",
    category: "bumpers",
    brand: "Rampage",
    name: "Rock Rage Front Bumper",
    variant: "Stubby",
    reference: "Quadratec JL bumper listing",
    priceCents: 29999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and whether a separate winch plate is required."
  },
  {
    id: "mopar-rubicon-steel-front-bumper",
    category: "bumpers",
    brand: "Mopar",
    name: "Three-Piece Rubicon Steel Front Bumper",
    variant: "Factory-style steel",
    reference: "Quadratec JL bumper listing",
    priceCents: 107099,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm original fog-light style, end caps, winch plate requirements, skid plate and harness details."
  },
  {
    id: "fab-fours-stubby-front-bumper",
    category: "bumpers",
    brand: "Fab Fours",
    name: "Stubby Front Bumper",
    variant: "Winch ready",
    reference: "Quadratec JL bumper listing",
    priceCents: 55799,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { winchMount: true },
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and exact winch fit before purchase."
  },
  {
    id: "fab-fours-ghost-front-bumper",
    category: "bumpers",
    brand: "Fab Fours",
    name: "Ghost Front Bumper",
    variant: "Mid-width",
    reference: "Quadratec JL bumper listing",
    priceCents: 45999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and whether a separate winch plate is required."
  },
  {
    id: "warn-elite-full-width-front-bumper",
    category: "bumpers",
    brand: "WARN",
    name: "Elite Series Full Width Front Bumper",
    variant: "Winch ready",
    reference: "Quadratec JL bumper listing",
    priceCents: 137999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { winchMount: true },
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and exact winch fit before purchase."
  },
  {
    id: "rugged-ridge-xor-front-bumper",
    category: "bumpers",
    brand: "Rugged Ridge",
    name: "XOR Front Bumper",
    variant: "Winch ready",
    reference: "Quadratec JL bumper listing",
    priceCents: 41999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { winchMount: true },
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and exact winch fit before purchase."
  },
  {
    id: "rampage-double-tube-front-bumper",
    category: "bumpers",
    brand: "Rampage",
    name: "Double Tube Front Bumper",
    variant: "Stainless",
    reference: "Quadratec JL bumper listing",
    priceCents: 28999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Tube bumpers can change recovery and winch options; confirm mounting and local inspection rules before purchase."
  },
  {
    id: "aries-trailcrusher-front-bumper",
    category: "bumpers",
    brand: "Aries",
    name: "TrailCrusher Front Bumper",
    variant: "Black",
    reference: "Quadratec JL bumper listing",
    priceCents: 25799,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and whether a separate winch plate is required."
  },
  {
    id: "dv8-oe-plus-front-bumper",
    category: "bumpers",
    brand: "DV8 Offroad",
    name: "OE Plus Front Bumper",
    variant: "Factory-style",
    reference: "Quadratec JL bumper listing",
    priceCents: 84999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and whether a separate winch plate is required."
  },
  {
    id: "smittybilt-gen2-src-classic-overrider",
    category: "bumpers",
    brand: "Smittybilt",
    name: "Gen2 SRC Classic Front Bumper",
    variant: "Overrider",
    reference: "Quadratec JL bumper listing",
    priceCents: 51999,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { winchMount: true },
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and exact winch fit before purchase."
  },
  {
    id: "arb-bondi-deluxe-front-bumper",
    category: "bumpers",
    brand: "ARB",
    name: "Bondi Deluxe Front Bumper",
    variant: "Full width",
    reference: "Quadratec JL bumper listing",
    priceCents: 149595,
    retailer: "Quadratec",
    url: sources.bumpers,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: { winchMount: true },
    notes: "Source listing snapshot. Confirm fog-light brackets, sensor clearance, recovery points and exact winch fit before purchase."
  },
  {
    id: "smittybilt-x2o-gen3-12k-synthetic",
    category: "winches",
    brand: "Smittybilt",
    name: "X2O GEN3",
    variant: "12,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 69999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "rugged-ridge-trekker-12500-synthetic",
    category: "winches",
    brand: "Rugged Ridge",
    name: "Trekker",
    variant: "12,500 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 68299,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "warn-zeon-10s-synthetic",
    category: "winches",
    brand: "WARN",
    name: "Zeon 10-S",
    variant: "10,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 154999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "quadratec-stealth-10k-synthetic",
    category: "winches",
    brand: "Quadratec",
    name: "Stealth Winch",
    variant: "10,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 49999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "quadratec-q-performance-stealth-12k",
    category: "winches",
    brand: "Quadratec",
    name: "Q-Performance Stealth Winch",
    variant: "12,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 69999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "superwinch-sx10sr-synthetic",
    category: "winches",
    brand: "Superwinch",
    name: "SX10SR",
    variant: "10,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 58499,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "smittybilt-x20-gen2-10k-synthetic",
    category: "winches",
    brand: "Smittybilt",
    name: "X20 GEN2",
    variant: "10,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 58999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "warn-zeon-platinum-12s-synthetic",
    category: "winches",
    brand: "WARN",
    name: "Zeon Platinum 12-S",
    variant: "12,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 264999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "superwinch-sx12sr-synthetic",
    category: "winches",
    brand: "Superwinch",
    name: "SX12SR",
    variant: "12,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 64799,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "warn-vr-evo-12s-synthetic",
    category: "winches",
    brand: "WARN",
    name: "VR EVO 12-S",
    variant: "12,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 104999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "warn-vr-evo-10-steel",
    category: "winches",
    brand: "WARN",
    name: "VR EVO 10",
    variant: "10,000 lb - Steel cable",
    reference: "Quadratec JL winch listing",
    priceCents: 79999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "smittybilt-xrc-gen3-12k-synthetic",
    category: "winches",
    brand: "Smittybilt",
    name: "XRC GEN3",
    variant: "12,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 64999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "warn-vr-evo-8s-synthetic",
    category: "winches",
    brand: "WARN",
    name: "VR EVO 8-S",
    variant: "8,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 84999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "smittybilt-x2o-gen3-10k-synthetic",
    category: "winches",
    brand: "Smittybilt",
    name: "X2O GEN3",
    variant: "10,000 lb - Synthetic rope",
    reference: "Quadratec JL winch listing",
    priceCents: 62999,
    retailer: "Quadratec",
    url: sources.winches,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Requires a rated winch mount, electrical installation, battery/charging review and exact bumper clearance check."
  },
  {
    id: "romik-ral-b-side-steps",
    category: "armor",
    brand: "Romik",
    name: "RAL-B Side Steps",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 83499,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "oedro-rocker-guards",
    category: "armor",
    brand: "OEDRO",
    name: "Rocker Guards",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 39599,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "quadratec-diver-down-side-step-covers",
    category: "armor",
    brand: "Quadratec",
    name: "Diver Down Neoprene Side Step Covers",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 4999,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Accessory covers only; confirm they fit the step or rail already on the vehicle."
  },
  {
    id: "go-rhino-dominator-extreme-d6",
    category: "armor",
    brand: "Go Rhino",
    name: "Dominator Extreme D6",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 48699,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "more-hide-a-step",
    category: "armor",
    brand: "M.O.R.E.",
    name: "Hide-A-Step",
    variant: "Bolt-on step",
    reference: "Quadratec JL rocker listing",
    priceCents: 11399,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Single-step accessory; confirm mount position and clearance with existing rails."
  },
  {
    id: "go-rhino-dominator-dss",
    category: "armor",
    brand: "Go Rhino",
    name: "Dominator DSS",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 37599,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "amp-research-powerstep-smartseries",
    category: "armor",
    brand: "AMP Research",
    name: "PowerStep SmartSeries",
    variant: "JL four-door",
    reference: "Quadratec JL rocker listing",
    priceCents: 199999,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Power steps need wiring, module placement and water-ingress review before trail use."
  },
  {
    id: "rough-country-hd2-running-boards",
    category: "armor",
    brand: "Rough Country",
    name: "HD2 Running Boards",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 49995,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "go-rhino-rb20-running-boards",
    category: "armor",
    brand: "Go Rhino",
    name: "RB20 Running Boards",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 60499,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "westin-hdx-xtreme-running-boards",
    category: "armor",
    brand: "Westin",
    name: "HDX Xtreme Running Boards",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 53999,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "barricade-trail-force-hd-rocker-steps",
    category: "armor",
    brand: "Barricade",
    name: "Trail Force HD Rocker Steps",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 35999,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "body-armor-pro-series-rock-sliders",
    category: "armor",
    brand: "Body Armor 4x4",
    name: "Pro-Series Rock Sliders",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 79799,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "westin-outlaw-drop-nerf-step-bars",
    category: "armor",
    brand: "Westin",
    name: "Outlaw Drop Nerf Step Bars",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 49499,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  },
  {
    id: "go-rhino-rockline-steps",
    category: "armor",
    brand: "Go Rhino",
    name: "Rockline Steps",
    variant: "JL four-door - Pair",
    reference: "Quadratec JL rocker listing",
    priceCents: 101799,
    retailer: "Quadratec",
    url: sources.armor,
    checkedAt,
    yearFrom: 2018,
    yearTo: 2026,
    trims,
    powertrains: bothPowertrains,
    specs: {},
    notes: "Source listing snapshot. Confirm drilling, rocker clearance, door clearance and whether factory rock rails must be removed."
  }
];

export default catalogExpansion;
